services:
  - type: web
    name: genieacs-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    buildCommand: docker build -t genieacs-api .
    startCommand: /entrypoint.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: GENIEACS_MONGODB_CONNECTION_URL
        sync: false
      - key: GENIEACS_CWMP_WORKER_PROCESSES
        value: "1"
      - key: GENIEACS_NBI_WORKER_PROCESSES
        value: "1"
    autoDeploy: true
    plan: free
